[package]
name = "git-delta"
authors = ["Dan Davison <dandavison7@gmail.com>"]
categories = ["command-line-utilities", "development-tools"]
description = "A syntax-highlighting pager for git"
documentation = "https://github.com/dandavison/delta"
edition = "2018"
homepage = "https://github.com/dandavison/delta"
license = "MIT"
repository = "https://github.com/dandavison/delta"
version = "0.7.1"

[[bin]]
name = "delta"
path = "src/main.rs"

[dependencies]
ansi_colours = "1.0.1"
ansi_term = "0.12.1"
atty = "0.2.14"
bitflags = "1.2.1"
box_drawing = "0.1.2"
bytelines = "2.2.2"
console = "0.14.1"
dirs-next = "2.0.0"
itertools = "0.10.0"
lazy_static = "1.4"
regex = "1.4.5"
shell-words = "1.0.0"
structopt = "0.3.21"
unicode-segmentation = "1.7.1"
unicode-width = "0.1.8"
vte = "0.10.0"
xdg = "2.2.0"

[dependencies.git2]
version = "0.13.17"
default-features = false
features = []

[dependencies.syntect]
version = "4.5.0"
default-features = false
features = ["parsing", "assets", "yaml-load", "dump-load", "regex-onig"]

[dependencies.error-chain]
version = "0.12.4"
default-features = false
features = []
