[package]
name = "git-delta"
authors = ["Dan Davison <dandavison7@gmail.com>"]
categories = ["command-line-utilities", "development-tools"]
description = "A syntax-highlighting pager for git"
documentation = "https://github.com/dandavison/delta"
edition = "2018"
homepage = "https://github.com/dandavison/delta"
license = "MIT"
readme = "README.md"
repository = "https://github.com/dandavison/delta"
version = "0.0.14"

[[bin]]
name = "delta"
path = "src/main.rs"

[dependencies]
ansi_term = "0.11.0"
atty = "0.2.13"
box_drawing = "0.1.2"
console = "0.7.7"
itertools = "0.8.0"
regex = "1.2.1"
shell-words = "0.1.0"
structopt = "0.2.18"
syntect = "3.2.0"
unicode-segmentation = "1.3.0"
unicode-width = "0.1.6"

[dependencies.error-chain]
version = "0.12.1"
default-features = false
features = []
