[package]
name = "git-delta"
authors = ["Dan Davison <dandavison7@gmail.com>"]
categories = ["command-line-utilities", "development-tools"]
description = "A syntax-highlighting pager for git"
documentation = "https://github.com/dandavison/delta"
edition = "2018"
homepage = "https://github.com/dandavison/delta"
license = "MIT"
repository = "https://github.com/dandavison/delta"
version = "0.11.2"

[[bin]]
name = "delta"
path = "src/main.rs"

[dependencies]
chrono = "0.4.19"
chrono-humanize = "0.2.1"
ansi_colours = "1.0.4"
ansi_term = "0.12.1"
atty = "0.2.14"
bitflags = "1.3.2"
box_drawing = "0.1.2"
bytelines = "2.2.2"
console = "0.15.0"
ctrlc = "3.2.1"
dirs-next = "2.0.0"
grep-cli = "0.1.6"
itertools = "0.10.1"
lazy_static = "1.4"
palette = "0.6.0"
pathdiff = "0.2.1"
regex = "1.4.6"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.70"
shell-words = "1.0.0"
smol_str = "0.1.21"
structopt = "0.3.25"
unicode-segmentation = "1.8.0"
unicode-width = "0.1.9"
vte = "0.10.1"
xdg = "2.4.0"

[dependencies.git2]
version = "0.13.23"
default-features = false
features = []

[dependencies.syntect]
version = "4.6.0"
default-features = false
features = ["parsing", "assets", "yaml-load", "dump-load", "regex-onig"]

[dependencies.sysinfo]
git = "https://github.com/GuillaumeGomez/sysinfo"
branch = "specific-process-update"
# no default features to disable the use of threads
default-features = false
features = []

[dependencies.error-chain]
version = "0.12.4"
default-features = false
features = []
