[package]
name = "git-delta"
authors = ["Dan Davison <dandavison7@gmail.com>"]
categories = ["command-line-utilities", "development-tools"]
description = "A syntax-highlighting pager for git"
documentation = "https://github.com/dandavison/delta"
edition = "2018"
homepage = "https://github.com/dandavison/delta"
license = "MIT"
readme = "README.md"
repository = "https://github.com/dandavison/delta"
version = "0.1.1"

[[bin]]
name = "delta"
path = "src/main.rs"

[dependencies]
ansi_colours = "1.0.1"
ansi-parser = "0.6.5"
ansi_term = "0.12.1"
atty = "0.2.14"
box_drawing = "0.1.2"
bytelines = "2.2.2"
console = "0.11.2"
dirs = "2.0"
itertools = "0.9.0"
lazy_static = "1.4"
regex = "1.2.1"
shell-words = "1.0.0"
structopt = "0.3.14"
unicode-segmentation = "1.6.0"
unicode-width = "0.1.7"

[dependencies.syntect]
version = "4.1.1"
default-features = false
features = ["parsing", "assets", "yaml-load", "dump-load", "regex-onig"]

[dependencies.error-chain]
version = "0.12.2"
default-features = false
features = []
